# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoomWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QListWidget, QListView, QTreeWidget, QTreeView,QFrame {\n"
"    outline: 0px;\n"
"}\n"
"/*设置左侧选项的最小最大宽度,文字颜色和背景颜色*/\n"
"#listWidget {\n"
"    min-width: 200px;\n"
"    max-width: 200px;\n"
"    color: white;\n"
"    background-color:#2f4050\n"
"}\n"
"#head\n"
"{\n"
"background:white;\n"
"border-radius:30px;\n"
"}\n"
"#head_2\n"
"{\n"
"background:#CCFFCC;\n"
"border:1px solid;\n"
"border-color:#CCFFCC;\n"
"border-radius:60px;\n"
"}\n"
"#Search\n"
"{\n"
"border-radius:5px;\n"
"background:#293846;\n"
"border:0.5px solid;\n"
"border-color:white;\n"
"\n"
"}\n"
"#listWidget::item\n"
"{\n"
"height:60;\n"
"background-color:#293846;\n"
"}\n"
"#frame\n"
"{\n"
"background-color:#2f4050\n"
"\n"
"}\n"
"/*被选中时的背景颜色和左边框颜色*/\n"
"#listWidget::item:selected {\n"
"    background: rgb(52, 52, 52);\n"
"    border-left: 2px solid rgb(9, 187, 7);\n"
"}\n"
"/*鼠标悬停颜色*/\n"
"HistoryPanel::item:hover {\n"
"    background: rgb(52, 52, 52);\n"
"}\n"
"/*右侧的层叠窗口的背景颜色*/\n"
"QStackedWidget {\n"
"    background: white;\n"
"}\n"
"/*模拟的页面*/\n"
"#frame > QLabel\n"
"{\n"
"color:white;\n"
"}\n"
"#frame_2\n"
"{\n"
"background-color:#CCFFCC;\n"
"}\n"
"#page_2 > QLineEdit\n"
"{\n"
"border-radius:5px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#6699CC;\n"
"}\n"
"QLineEdit\n"
"{\n"
"border-radius:5px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#6699CC;\n"
"}\n"
"QComboBox,QDateEdit\n"
"{\n"
"border-radius:5px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#6699CC;\n"
"}\n"
"#listWidget_2,#listWidget_3,#listWidget_4\n"
"{\n"
"background-color:#CCFFFF;\n"
"border:1px solid black\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 200, 204, 400))
        self.listWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../pictures/room1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../pictures/room2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../pictures/room4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../pictures/room5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../pictures/room3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 204, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.head = QtWidgets.QToolButton(self.frame)
        self.head.setGeometry(QtCore.QRect(60, 20, 60, 60))
        self.head.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../pictures/staff3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.head.setIcon(icon5)
        self.head.setIconSize(QtCore.QSize(60, 60))
        self.head.setObjectName("head")
        self.welcome = QtWidgets.QLabel(self.frame)
        self.welcome.setGeometry(QtCore.QRect(30, 90, 110, 20))
        self.welcome.setText("")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Search = QtWidgets.QLineEdit(self.frame)
        self.Search.setGeometry(QtCore.QRect(20, 170, 145, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Search.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.Search.setFont(font)
        self.Search.setStyleSheet("")
        self.Search.setObjectName("Search")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(170, 170, 21, 20))
        self.toolButton.setStyleSheet("background-color:#2f4050;\n"
"border:0px;\n"
"\n"
"border-radius:5px")
        self.toolButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../pictures/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setIconSize(QtCore.QSize(15, 15))
        self.toolButton.setObjectName("toolButton")
        self.role = QtWidgets.QLabel(self.frame)
        self.role.setGeometry(QtCore.QRect(30, 120, 110, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.role.setFont(font)
        self.role.setText("")
        self.role.setAlignment(QtCore.Qt.AlignCenter)
        self.role.setObjectName("role")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.toolButton_2 = QtWidgets.QToolButton(self.page)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("border:none")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../pictures/search1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon7)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.split_2 = QtWidgets.QFrame(self.page)
        self.split_2.setGeometry(QtCore.QRect(0, 30, 600, 2))
        self.split_2.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_2.setObjectName("split_2")
        self.inputType = QtWidgets.QComboBox(self.page)
        self.inputType.setGeometry(QtCore.QRect(100, 50, 131, 22))
        self.inputType.setObjectName("inputType")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setGeometry(QtCore.QRect(40, 50, 41, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page)
        self.label_23.setGeometry(QtCore.QRect(300, 50, 71, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setGeometry(QtCore.QRect(300, 100, 101, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page)
        self.label_25.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.label_25.setObjectName("label_25")
        self.inputprice1 = QtWidgets.QLineEdit(self.page)
        self.inputprice1.setGeometry(QtCore.QRect(140, 180, 113, 21))
        self.inputprice1.setObjectName("inputprice1")
        self.label_26 = QtWidgets.QLabel(self.page)
        self.label_26.setGeometry(QtCore.QRect(260, 180, 21, 21))
        self.label_26.setObjectName("label_26")
        self.inputprice2 = QtWidgets.QLineEdit(self.page)
        self.inputprice2.setGeometry(QtCore.QRect(280, 180, 113, 21))
        self.inputprice2.setObjectName("inputprice2")
        self.label_27 = QtWidgets.QLabel(self.page)
        self.label_27.setGeometry(QtCore.QRect(40, 100, 101, 21))
        self.label_27.setObjectName("label_27")
        self.inputstorey = QtWidgets.QComboBox(self.page)
        self.inputstorey.setGeometry(QtCore.QRect(100, 100, 131, 22))
        self.inputstorey.setObjectName("inputstorey")
        self.inputstorey.addItem("")
        self.inputstorey.addItem("")
        self.inputstorey.addItem("")
        self.inputstorey.addItem("")
        self.inputStartTime = QtWidgets.QDateEdit(self.page)
        self.inputStartTime.setGeometry(QtCore.QRect(420, 100, 110, 22))
        self.inputStartTime.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inputStartTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.inputStartTime.setMaximumTime(QtCore.QTime(22, 59, 59))
        self.inputStartTime.setObjectName("inputStartTime")
        self.commitSearch = QtWidgets.QPushButton(self.page)
        self.commitSearch.setGeometry(QtCore.QRect(190, 210, 211, 31))
        self.commitSearch.setStyleSheet("#commitSearch{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitSearch:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitSearch.setObjectName("commitSearch")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(0, 250, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.inputFree = QtWidgets.QRadioButton(self.page)
        self.inputFree.setGeometry(QtCore.QRect(420, 50, 115, 19))
        self.inputFree.setObjectName("inputFree")
        self.inputEndTime = QtWidgets.QDateEdit(self.page)
        self.inputEndTime.setGeometry(QtCore.QRect(420, 140, 110, 22))
        self.inputEndTime.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inputEndTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.inputEndTime.setMaximumTime(QtCore.QTime(22, 59, 59))
        self.inputEndTime.setObjectName("inputEndTime")
        self.line_16 = QtWidgets.QFrame(self.page)
        self.line_16.setGeometry(QtCore.QRect(390, 140, 20, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setGeometry(QtCore.QRect(0, 260, 601, 341))
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setStyleSheet("background-color:white")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 580, 341))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.reset = QtWidgets.QPushButton(self.page)
        self.reset.setGeometry(QtCore.QRect(530, 220, 51, 31))
        self.reset.setStyleSheet("#reset{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#reset:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.reset.setObjectName("reset")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.page_2)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("border:none")
        self.toolButton_3.setIcon(icon7)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_2.setGeometry(QtCore.QRect(-10, 30, 611, 41))
        self.listWidget_2.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.stackedWidget_sub = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_sub.setGeometry(QtCore.QRect(0, 80, 601, 511))
        self.stackedWidget_sub.setObjectName("stackedWidget_sub")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.line_4 = QtWidgets.QFrame(self.page_6)
        self.line_4.setGeometry(QtCore.QRect(0, 240, 601, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.page_6)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cname = QtWidgets.QLineEdit(self.page_6)
        self.cname.setGeometry(QtCore.QRect(260, 40, 221, 21))
        self.cname.setObjectName("cname")
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(140, 110, 101, 41))
        self.label_13.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_13.setObjectName("label_13")
        self.cphone = QtWidgets.QLineEdit(self.page_6)
        self.cphone.setGeometry(QtCore.QRect(260, 120, 221, 21))
        self.cphone.setObjectName("cphone")
        self.label_9 = QtWidgets.QLabel(self.page_6)
        self.label_9.setGeometry(QtCore.QRect(140, 30, 101, 40))
        self.label_9.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setGeometry(QtCore.QRect(140, 70, 101, 41))
        self.label_11.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_11.setObjectName("label_11")
        self.cid = QtWidgets.QLineEdit(self.page_6)
        self.cid.setGeometry(QtCore.QRect(260, 80, 221, 21))
        self.cid.setObjectName("cid")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setGeometry(QtCore.QRect(140, 150, 101, 41))
        self.label_14.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setGeometry(QtCore.QRect(140, 190, 101, 41))
        self.label_15.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_15.setObjectName("label_15")
        self.cage = QtWidgets.QLineEdit(self.page_6)
        self.cage.setGeometry(QtCore.QRect(260, 160, 221, 21))
        self.cage.setObjectName("cage")
        self.crid = QtWidgets.QLineEdit(self.page_6)
        self.crid.setGeometry(QtCore.QRect(260, 290, 221, 21))
        self.crid.setText("")
        self.crid.setObjectName("crid")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setGeometry(QtCore.QRect(140, 280, 101, 40))
        self.label_10.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_10.setObjectName("label_10")
        self.endtime = QtWidgets.QDateEdit(self.page_6)
        self.endtime.setGeometry(QtCore.QRect(260, 350, 221, 22))
        self.endtime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.endtime.setObjectName("endtime")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setGeometry(QtCore.QRect(140, 340, 121, 41))
        self.label_16.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(140, 400, 101, 41))
        self.label_17.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_17.setObjectName("label_17")
        self.remark = QtWidgets.QLineEdit(self.page_6)
        self.remark.setGeometry(QtCore.QRect(260, 410, 221, 21))
        self.remark.setText("")
        self.remark.setPlaceholderText("")
        self.remark.setObjectName("remark")
        self.commitCheckin = QtWidgets.QPushButton(self.page_6)
        self.commitCheckin.setGeometry(QtCore.QRect(230, 460, 211, 31))
        self.commitCheckin.setStyleSheet("#commitCheckin{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitCheckin:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitCheckin.setObjectName("commitCheckin")
        self.male = QtWidgets.QRadioButton(self.page_6)
        self.male.setGeometry(QtCore.QRect(260, 200, 81, 19))
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(self.page_6)
        self.female.setGeometry(QtCore.QRect(360, 200, 115, 19))
        self.female.setObjectName("female")
        self.stackedWidget_sub.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.line_5 = QtWidgets.QFrame(self.page_7)
        self.line_5.setGeometry(QtCore.QRect(0, 240, 601, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        self.label_12.setGeometry(QtCore.QRect(140, 30, 101, 40))
        self.label_12.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_12.setObjectName("label_12")
        self.label_4 = QtWidgets.QLabel(self.page_7)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_18 = QtWidgets.QLabel(self.page_7)
        self.label_18.setGeometry(QtCore.QRect(140, 130, 121, 41))
        self.label_18.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_18.setObjectName("label_18")
        self.tphone = QtWidgets.QLineEdit(self.page_7)
        self.tphone.setGeometry(QtCore.QRect(260, 140, 221, 21))
        self.tphone.setObjectName("tphone")
        self.label_19 = QtWidgets.QLabel(self.page_7)
        self.label_19.setGeometry(QtCore.QRect(140, 280, 101, 40))
        self.label_19.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_19.setObjectName("label_19")
        self.tremark = QtWidgets.QLineEdit(self.page_7)
        self.tremark.setGeometry(QtCore.QRect(260, 410, 221, 21))
        self.tremark.setText("")
        self.tremark.setPlaceholderText("")
        self.tremark.setObjectName("tremark")
        self.label_5 = QtWidgets.QLabel(self.page_7)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tname = QtWidgets.QLineEdit(self.page_7)
        self.tname.setGeometry(QtCore.QRect(260, 40, 221, 21))
        self.tname.setObjectName("tname")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setGeometry(QtCore.QRect(140, 80, 101, 41))
        self.label_21.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_21.setObjectName("label_21")
        self.tendtime = QtWidgets.QDateEdit(self.page_7)
        self.tendtime.setGeometry(QtCore.QRect(260, 350, 221, 22))
        self.tendtime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.tendtime.setObjectName("tendtime")
        self.label_29 = QtWidgets.QLabel(self.page_7)
        self.label_29.setGeometry(QtCore.QRect(140, 340, 101, 41))
        self.label_29.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_29.setObjectName("label_29")
        self.tid = QtWidgets.QLineEdit(self.page_7)
        self.tid.setGeometry(QtCore.QRect(260, 90, 221, 21))
        self.tid.setObjectName("tid")
        self.trid = QtWidgets.QLineEdit(self.page_7)
        self.trid.setGeometry(QtCore.QRect(260, 290, 221, 21))
        self.trid.setText("")
        self.trid.setObjectName("trid")
        self.commitCheckinTeam = QtWidgets.QPushButton(self.page_7)
        self.commitCheckinTeam.setGeometry(QtCore.QRect(230, 460, 211, 31))
        self.commitCheckinTeam.setStyleSheet("#commitCheckinTeam{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitCheckinTeam:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitCheckinTeam.setObjectName("commitCheckinTeam")
        self.label_30 = QtWidgets.QLabel(self.page_7)
        self.label_30.setGeometry(QtCore.QRect(140, 400, 101, 41))
        self.label_30.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_30.setObjectName("label_30")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        self.label_6.setGeometry(QtCore.QRect(260, 315, 211, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget_sub.addWidget(self.page_7)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.line_6 = QtWidgets.QFrame(self.page_10)
        self.line_6.setGeometry(QtCore.QRect(0, 230, 601, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_46 = QtWidgets.QLabel(self.page_10)
        self.label_46.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_10)
        self.label_47.setGeometry(QtCore.QRect(10, 250, 131, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_10)
        self.label_48.setGeometry(QtCore.QRect(100, 70, 191, 40))
        self.label_48.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_48.setObjectName("label_48")
        self.cid_rtc = QtWidgets.QLineEdit(self.page_10)
        self.cid_rtc.setGeometry(QtCore.QRect(280, 80, 221, 21))
        self.cid_rtc.setObjectName("cid_rtc")
        self.label_49 = QtWidgets.QLabel(self.page_10)
        self.label_49.setGeometry(QtCore.QRect(100, 120, 191, 40))
        self.label_49.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_49.setObjectName("label_49")
        self.crid_rtc = QtWidgets.QLineEdit(self.page_10)
        self.crid_rtc.setGeometry(QtCore.QRect(280, 130, 221, 21))
        self.crid_rtc.setObjectName("crid_rtc")
        self.tid_rtc = QtWidgets.QLineEdit(self.page_10)
        self.tid_rtc.setGeometry(QtCore.QRect(280, 310, 221, 21))
        self.tid_rtc.setObjectName("tid_rtc")
        self.label_50 = QtWidgets.QLabel(self.page_10)
        self.label_50.setGeometry(QtCore.QRect(100, 300, 191, 40))
        self.label_50.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_50.setObjectName("label_50")
        self.trid_rtc = QtWidgets.QLineEdit(self.page_10)
        self.trid_rtc.setGeometry(QtCore.QRect(280, 360, 221, 21))
        self.trid_rtc.setObjectName("trid_rtc")
        self.label_51 = QtWidgets.QLabel(self.page_10)
        self.label_51.setGeometry(QtCore.QRect(100, 350, 191, 40))
        self.label_51.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_10)
        self.label_52.setGeometry(QtCore.QRect(290, 390, 211, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.commitrtcC = QtWidgets.QPushButton(self.page_10)
        self.commitrtcC.setGeometry(QtCore.QRect(220, 180, 211, 31))
        self.commitrtcC.setStyleSheet("#commitrtcC{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitrtcC:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitrtcC.setObjectName("commitrtcC")
        self.commitrtcT = QtWidgets.QPushButton(self.page_10)
        self.commitrtcT.setGeometry(QtCore.QRect(220, 430, 211, 31))
        self.commitrtcT.setStyleSheet("#commitrtcT{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitrtcT:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitrtcT.setObjectName("commitrtcT")
        self.stackedWidget_sub.addWidget(self.page_10)
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(60, 40, 20, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setGeometry(QtCore.QRect(140, 40, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.page_3)
        self.toolButton_4.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("border:none")
        self.toolButton_4.setIcon(icon7)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.split_4 = QtWidgets.QFrame(self.page_3)
        self.split_4.setGeometry(QtCore.QRect(0, 30, 600, 2))
        self.split_4.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_4.setObjectName("split_4")
        self.stackedWidget_sub_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_sub_2.setGeometry(QtCore.QRect(0, 70, 601, 531))
        self.stackedWidget_sub_2.setObjectName("stackedWidget_sub_2")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.line_7 = QtWidgets.QFrame(self.page_8)
        self.line_7.setGeometry(QtCore.QRect(0, 240, 601, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_7 = QtWidgets.QLabel(self.page_8)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_8)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cname_booking = QtWidgets.QLineEdit(self.page_8)
        self.cname_booking.setGeometry(QtCore.QRect(260, 50, 221, 21))
        self.cname_booking.setObjectName("cname_booking")
        self.label_20 = QtWidgets.QLabel(self.page_8)
        self.label_20.setGeometry(QtCore.QRect(140, 120, 101, 41))
        self.label_20.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_20.setObjectName("label_20")
        self.cphone_booking = QtWidgets.QLineEdit(self.page_8)
        self.cphone_booking.setGeometry(QtCore.QRect(260, 130, 221, 21))
        self.cphone_booking.setObjectName("cphone_booking")
        self.label_28 = QtWidgets.QLabel(self.page_8)
        self.label_28.setGeometry(QtCore.QRect(140, 40, 101, 40))
        self.label_28.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_28.setObjectName("label_28")
        self.label_31 = QtWidgets.QLabel(self.page_8)
        self.label_31.setGeometry(QtCore.QRect(140, 80, 101, 41))
        self.label_31.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_31.setObjectName("label_31")
        self.cid_booking = QtWidgets.QLineEdit(self.page_8)
        self.cid_booking.setGeometry(QtCore.QRect(260, 90, 221, 21))
        self.cid_booking.setObjectName("cid_booking")
        self.label_32 = QtWidgets.QLabel(self.page_8)
        self.label_32.setGeometry(QtCore.QRect(140, 160, 101, 41))
        self.label_32.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_8)
        self.label_33.setGeometry(QtCore.QRect(140, 200, 101, 41))
        self.label_33.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_33.setObjectName("label_33")
        self.cage_booking = QtWidgets.QLineEdit(self.page_8)
        self.cage_booking.setGeometry(QtCore.QRect(260, 170, 221, 21))
        self.cage_booking.setObjectName("cage_booking")
        self.crid_booking = QtWidgets.QLineEdit(self.page_8)
        self.crid_booking.setGeometry(QtCore.QRect(260, 290, 221, 21))
        self.crid_booking.setText("")
        self.crid_booking.setObjectName("crid_booking")
        self.label_34 = QtWidgets.QLabel(self.page_8)
        self.label_34.setGeometry(QtCore.QRect(140, 280, 101, 40))
        self.label_34.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_34.setObjectName("label_34")
        self.starttime_booking = QtWidgets.QDateEdit(self.page_8)
        self.starttime_booking.setGeometry(QtCore.QRect(260, 340, 221, 22))
        self.starttime_booking.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.starttime_booking.setObjectName("starttime_booking")
        self.label_35 = QtWidgets.QLabel(self.page_8)
        self.label_35.setGeometry(QtCore.QRect(140, 330, 101, 41))
        self.label_35.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_35.setObjectName("label_35")
        self.endtime_booking = QtWidgets.QDateEdit(self.page_8)
        self.endtime_booking.setGeometry(QtCore.QRect(260, 380, 221, 22))
        self.endtime_booking.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.endtime_booking.setObjectName("endtime_booking")
        self.line_8 = QtWidgets.QFrame(self.page_8)
        self.line_8.setGeometry(QtCore.QRect(220, 380, 31, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_36 = QtWidgets.QLabel(self.page_8)
        self.label_36.setGeometry(QtCore.QRect(140, 410, 101, 41))
        self.label_36.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_36.setObjectName("label_36")
        self.remark_booking = QtWidgets.QLineEdit(self.page_8)
        self.remark_booking.setGeometry(QtCore.QRect(260, 420, 221, 21))
        self.remark_booking.setText("")
        self.remark_booking.setPlaceholderText("")
        self.remark_booking.setObjectName("remark_booking")
        self.commitBookingClient = QtWidgets.QPushButton(self.page_8)
        self.commitBookingClient.setGeometry(QtCore.QRect(230, 470, 211, 31))
        self.commitBookingClient.setStyleSheet("#commitBookingClient{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitBookingClient:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitBookingClient.setObjectName("commitBookingClient")
        self.male_booking = QtWidgets.QRadioButton(self.page_8)
        self.male_booking.setGeometry(QtCore.QRect(260, 210, 81, 19))
        self.male_booking.setObjectName("male_booking")
        self.female_booking = QtWidgets.QRadioButton(self.page_8)
        self.female_booking.setGeometry(QtCore.QRect(360, 210, 115, 19))
        self.female_booking.setObjectName("female_booking")
        self.stackedWidget_sub_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.tendtime_booking = QtWidgets.QDateEdit(self.page_9)
        self.tendtime_booking.setGeometry(QtCore.QRect(260, 380, 221, 22))
        self.tendtime_booking.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.tendtime_booking.setObjectName("tendtime_booking")
        self.line_9 = QtWidgets.QFrame(self.page_9)
        self.line_9.setGeometry(QtCore.QRect(0, 240, 601, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_37 = QtWidgets.QLabel(self.page_9)
        self.label_37.setGeometry(QtCore.QRect(140, 40, 101, 40))
        self.label_37.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_9)
        self.label_38.setGeometry(QtCore.QRect(20, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.page_9)
        self.label_39.setGeometry(QtCore.QRect(140, 140, 121, 41))
        self.label_39.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_39.setObjectName("label_39")
        self.tphone_booking = QtWidgets.QLineEdit(self.page_9)
        self.tphone_booking.setGeometry(QtCore.QRect(260, 150, 221, 21))
        self.tphone_booking.setObjectName("tphone_booking")
        self.label_40 = QtWidgets.QLabel(self.page_9)
        self.label_40.setGeometry(QtCore.QRect(140, 280, 101, 40))
        self.label_40.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_40.setObjectName("label_40")
        self.line_10 = QtWidgets.QFrame(self.page_9)
        self.line_10.setGeometry(QtCore.QRect(220, 380, 31, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tremark_booking = QtWidgets.QLineEdit(self.page_9)
        self.tremark_booking.setGeometry(QtCore.QRect(260, 420, 221, 21))
        self.tremark_booking.setText("")
        self.tremark_booking.setPlaceholderText("")
        self.tremark_booking.setObjectName("tremark_booking")
        self.label_41 = QtWidgets.QLabel(self.page_9)
        self.label_41.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tname_booking = QtWidgets.QLineEdit(self.page_9)
        self.tname_booking.setGeometry(QtCore.QRect(260, 50, 221, 21))
        self.tname_booking.setObjectName("tname_booking")
        self.label_42 = QtWidgets.QLabel(self.page_9)
        self.label_42.setGeometry(QtCore.QRect(140, 90, 101, 41))
        self.label_42.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_42.setObjectName("label_42")
        self.tstarttime_booking = QtWidgets.QDateEdit(self.page_9)
        self.tstarttime_booking.setGeometry(QtCore.QRect(260, 340, 221, 22))
        self.tstarttime_booking.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.tstarttime_booking.setObjectName("tstarttime_booking")
        self.label_43 = QtWidgets.QLabel(self.page_9)
        self.label_43.setGeometry(QtCore.QRect(140, 330, 101, 41))
        self.label_43.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_43.setObjectName("label_43")
        self.tid_booking = QtWidgets.QLineEdit(self.page_9)
        self.tid_booking.setGeometry(QtCore.QRect(260, 100, 221, 21))
        self.tid_booking.setObjectName("tid_booking")
        self.trid_booking = QtWidgets.QLineEdit(self.page_9)
        self.trid_booking.setGeometry(QtCore.QRect(260, 290, 221, 21))
        self.trid_booking.setText("")
        self.trid_booking.setObjectName("trid_booking")
        self.commitBookingTeam = QtWidgets.QPushButton(self.page_9)
        self.commitBookingTeam.setGeometry(QtCore.QRect(230, 470, 211, 31))
        self.commitBookingTeam.setStyleSheet("#commitBookingTeam{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitBookingTeam:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitBookingTeam.setObjectName("commitBookingTeam")
        self.label_44 = QtWidgets.QLabel(self.page_9)
        self.label_44.setGeometry(QtCore.QRect(140, 410, 101, 41))
        self.label_44.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.page_9)
        self.label_45.setGeometry(QtCore.QRect(260, 315, 211, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.stackedWidget_sub_2.addWidget(self.page_9)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.cid_deb = QtWidgets.QLineEdit(self.page_11)
        self.cid_deb.setGeometry(QtCore.QRect(280, 90, 221, 21))
        self.cid_deb.setObjectName("cid_deb")
        self.label_53 = QtWidgets.QLabel(self.page_11)
        self.label_53.setGeometry(QtCore.QRect(290, 400, 211, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_11)
        self.label_54.setGeometry(QtCore.QRect(100, 80, 191, 40))
        self.label_54.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_54.setObjectName("label_54")
        self.commitDeBookT = QtWidgets.QPushButton(self.page_11)
        self.commitDeBookT.setGeometry(QtCore.QRect(220, 440, 211, 31))
        self.commitDeBookT.setStyleSheet("#commitDeBookT{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitDeBookT:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitDeBookT.setObjectName("commitDeBookT")
        self.label_55 = QtWidgets.QLabel(self.page_11)
        self.label_55.setGeometry(QtCore.QRect(10, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_11)
        self.label_56.setGeometry(QtCore.QRect(100, 310, 191, 40))
        self.label_56.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_56.setObjectName("label_56")
        self.commitDeBookC = QtWidgets.QPushButton(self.page_11)
        self.commitDeBookC.setGeometry(QtCore.QRect(220, 190, 211, 31))
        self.commitDeBookC.setStyleSheet("#commitDeBookC{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitDeBookC:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitDeBookC.setObjectName("commitDeBookC")
        self.tid_deb = QtWidgets.QLineEdit(self.page_11)
        self.tid_deb.setGeometry(QtCore.QRect(280, 320, 221, 21))
        self.tid_deb.setObjectName("tid_deb")
        self.crid_deb = QtWidgets.QLineEdit(self.page_11)
        self.crid_deb.setGeometry(QtCore.QRect(280, 140, 221, 21))
        self.crid_deb.setObjectName("crid_deb")
        self.label_57 = QtWidgets.QLabel(self.page_11)
        self.label_57.setGeometry(QtCore.QRect(100, 360, 191, 40))
        self.label_57.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.page_11)
        self.label_58.setGeometry(QtCore.QRect(100, 130, 191, 40))
        self.label_58.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.page_11)
        self.label_59.setGeometry(QtCore.QRect(10, 260, 131, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.trid_deb = QtWidgets.QLineEdit(self.page_11)
        self.trid_deb.setGeometry(QtCore.QRect(280, 370, 221, 21))
        self.trid_deb.setObjectName("trid_deb")
        self.line_13 = QtWidgets.QFrame(self.page_11)
        self.line_13.setGeometry(QtCore.QRect(0, 240, 601, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.stackedWidget_sub_2.addWidget(self.page_11)
        self.listWidget_3 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_3.setGeometry(QtCore.QRect(-10, 30, 611, 41))
        self.listWidget_3.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.line_11 = QtWidgets.QFrame(self.page_3)
        self.line_11.setGeometry(QtCore.QRect(60, 40, 20, 21))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.page_3)
        self.line_12.setGeometry(QtCore.QRect(140, 40, 20, 21))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.page_4)
        self.toolButton_5.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setStyleSheet("border:none")
        self.toolButton_5.setIcon(icon7)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.split_5 = QtWidgets.QFrame(self.page_4)
        self.split_5.setGeometry(QtCore.QRect(0, 30, 600, 2))
        self.split_5.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_5.setObjectName("split_5")
        self.team_flag = QtWidgets.QRadioButton(self.page_4)
        self.team_flag.setGeometry(QtCore.QRect(400, 70, 115, 19))
        self.team_flag.setObjectName("team_flag")
        self.single_flag = QtWidgets.QRadioButton(self.page_4)
        self.single_flag.setGeometry(QtCore.QRect(300, 70, 81, 19))
        self.single_flag.setObjectName("single_flag")
        self.label_60 = QtWidgets.QLabel(self.page_4)
        self.label_60.setGeometry(QtCore.QRect(130, 60, 101, 41))
        self.label_60.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.page_4)
        self.label_61.setGeometry(QtCore.QRect(130, 110, 171, 41))
        self.label_61.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_61.setObjectName("label_61")
        self.id_checkout = QtWidgets.QLineEdit(self.page_4)
        self.id_checkout.setGeometry(QtCore.QRect(300, 120, 221, 21))
        self.id_checkout.setObjectName("id_checkout")
        self.remark_checkout = QtWidgets.QLineEdit(self.page_4)
        self.remark_checkout.setGeometry(QtCore.QRect(300, 420, 221, 21))
        self.remark_checkout.setText("")
        self.remark_checkout.setPlaceholderText("")
        self.remark_checkout.setObjectName("remark_checkout")
        self.label_62 = QtWidgets.QLabel(self.page_4)
        self.label_62.setGeometry(QtCore.QRect(130, 410, 101, 41))
        self.label_62.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_62.setObjectName("label_62")
        self.starttime_5 = QtWidgets.QDateEdit(self.page_4)
        self.starttime_5.setGeometry(QtCore.QRect(610, 170, 221, 22))
        self.starttime_5.setObjectName("starttime_5")
        self.endtime_5 = QtWidgets.QDateEdit(self.page_4)
        self.endtime_5.setGeometry(QtCore.QRect(610, 210, 221, 22))
        self.endtime_5.setObjectName("endtime_5")
        self.starttime_checkout = QtWidgets.QDateEdit(self.page_4)
        self.starttime_checkout.setGeometry(QtCore.QRect(300, 170, 221, 22))
        self.starttime_checkout.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.starttime_checkout.setObjectName("starttime_checkout")
        self.label_63 = QtWidgets.QLabel(self.page_4)
        self.label_63.setGeometry(QtCore.QRect(130, 160, 101, 41))
        self.label_63.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_63.setObjectName("label_63")
        self.endtime_checkout = QtWidgets.QDateEdit(self.page_4)
        self.endtime_checkout.setGeometry(QtCore.QRect(300, 230, 221, 22))
        self.endtime_checkout.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.endtime_checkout.setObjectName("endtime_checkout")
        self.rid_checkout = QtWidgets.QLineEdit(self.page_4)
        self.rid_checkout.setGeometry(QtCore.QRect(300, 290, 221, 21))
        self.rid_checkout.setText("")
        self.rid_checkout.setObjectName("rid_checkout")
        self.label_64 = QtWidgets.QLabel(self.page_4)
        self.label_64.setGeometry(QtCore.QRect(130, 280, 101, 40))
        self.label_64.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.page_4)
        self.label_65.setGeometry(QtCore.QRect(130, 350, 101, 41))
        self.label_65.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_65.setObjectName("label_65")
        self.paytype_checkout = QtWidgets.QLineEdit(self.page_4)
        self.paytype_checkout.setGeometry(QtCore.QRect(300, 360, 221, 21))
        self.paytype_checkout.setText("")
        self.paytype_checkout.setObjectName("paytype_checkout")
        self.commitCheckout = QtWidgets.QPushButton(self.page_4)
        self.commitCheckout.setGeometry(QtCore.QRect(220, 490, 211, 31))
        self.commitCheckout.setStyleSheet("#commitCheckout{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitCheckout:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitCheckout.setObjectName("commitCheckout")
        self.line_14 = QtWidgets.QFrame(self.page_4)
        self.line_14.setGeometry(QtCore.QRect(380, 200, 20, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_67 = QtWidgets.QLabel(self.page_4)
        self.label_67.setGeometry(QtCore.QRect(310, 310, 211, 16))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.page_5)
        self.toolButton_6.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setStyleSheet("border:none")
        self.toolButton_6.setIcon(icon7)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.split_6 = QtWidgets.QFrame(self.page_5)
        self.split_6.setGeometry(QtCore.QRect(0, 30, 600, 2))
        self.split_6.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_6.setObjectName("split_6")
        self.listWidget_4 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_4.setGeometry(QtCore.QRect(-10, 30, 611, 41))
        self.listWidget_4.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_4.setObjectName("listWidget_4")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.line_15 = QtWidgets.QFrame(self.page_5)
        self.line_15.setGeometry(QtCore.QRect(60, 40, 20, 21))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.stackedWidget_sub_3 = QtWidgets.QStackedWidget(self.page_5)
        self.stackedWidget_sub_3.setGeometry(QtCore.QRect(0, 70, 601, 541))
        self.stackedWidget_sub_3.setObjectName("stackedWidget_sub_3")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.commitAddRoom = QtWidgets.QPushButton(self.page_14)
        self.commitAddRoom.setGeometry(QtCore.QRect(210, 450, 211, 31))
        self.commitAddRoom.setStyleSheet("#commitAddRoom{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitAddRoom:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitAddRoom.setObjectName("commitAddRoom")
        self.label_71 = QtWidgets.QLabel(self.page_14)
        self.label_71.setGeometry(QtCore.QRect(120, 270, 121, 40))
        self.label_71.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_71.setObjectName("label_71")
        self.label_68 = QtWidgets.QLabel(self.page_14)
        self.label_68.setGeometry(QtCore.QRect(120, 90, 101, 40))
        self.label_68.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_68.setObjectName("label_68")
        self.label_70 = QtWidgets.QLabel(self.page_14)
        self.label_70.setGeometry(QtCore.QRect(120, 210, 101, 40))
        self.label_70.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_70.setObjectName("label_70")
        self.rprice_add = QtWidgets.QLineEdit(self.page_14)
        self.rprice_add.setGeometry(QtCore.QRect(250, 280, 221, 21))
        self.rprice_add.setText("")
        self.rprice_add.setObjectName("rprice_add")
        self.rid_add = QtWidgets.QLineEdit(self.page_14)
        self.rid_add.setGeometry(QtCore.QRect(250, 100, 221, 21))
        self.rid_add.setText("")
        self.rid_add.setObjectName("rid_add")
        self.rdesc_add = QtWidgets.QLineEdit(self.page_14)
        self.rdesc_add.setGeometry(QtCore.QRect(250, 340, 221, 21))
        self.rdesc_add.setText("")
        self.rdesc_add.setObjectName("rdesc_add")
        self.label_69 = QtWidgets.QLabel(self.page_14)
        self.label_69.setGeometry(QtCore.QRect(120, 150, 101, 40))
        self.label_69.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_69.setObjectName("label_69")
        self.label_72 = QtWidgets.QLabel(self.page_14)
        self.label_72.setGeometry(QtCore.QRect(120, 330, 101, 40))
        self.label_72.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_72.setObjectName("label_72")
        self.label_84 = QtWidgets.QLabel(self.page_14)
        self.label_84.setGeometry(QtCore.QRect(180, 20, 321, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.rtype_add = QtWidgets.QComboBox(self.page_14)
        self.rtype_add.setGeometry(QtCore.QRect(250, 160, 221, 22))
        self.rtype_add.setObjectName("rtype_add")
        self.rtype_add.addItem("")
        self.rtype_add.addItem("")
        self.rtype_add.addItem("")
        self.rtype_add.addItem("")
        self.rtype_add.addItem("")
        self.rstorey_add = QtWidgets.QComboBox(self.page_14)
        self.rstorey_add.setGeometry(QtCore.QRect(250, 220, 221, 22))
        self.rstorey_add.setObjectName("rstorey_add")
        self.rstorey_add.addItem("")
        self.rstorey_add.addItem("")
        self.rstorey_add.addItem("")
        self.rstorey_add.addItem("")
        self.label_66 = QtWidgets.QLabel(self.page_14)
        self.label_66.setGeometry(QtCore.QRect(120, 389, 121, 40))
        self.label_66.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_66.setObjectName("label_66")
        self.scan = QtWidgets.QPushButton(self.page_14)
        self.scan.setGeometry(QtCore.QRect(470, 395, 93, 28))
        self.scan.setStyleSheet("#scan{background:white\n"
";\n"
"border:1px solid black;\n"
"border-radius:8px}\n"
"#scan:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.scan.setObjectName("scan")
        self.path = QtWidgets.QLineEdit(self.page_14)
        self.path.setGeometry(QtCore.QRect(250, 400, 211, 21))
        self.path.setStyleSheet("border-radius:10px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#CCCCFF;\n"
"")
        self.path.setObjectName("path")
        self.stackedWidget_sub_3.addWidget(self.page_14)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.line_17 = QtWidgets.QFrame(self.page_12)
        self.line_17.setGeometry(QtCore.QRect(0, 120, 621, 21))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.frame_2 = QtWidgets.QFrame(self.page_12)
        self.frame_2.setGeometry(QtCore.QRect(-10, 0, 611, 131))
        self.frame_2.setStyleSheet("background-color:rgb(255, 249, 246)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.searchNB = QtWidgets.QToolButton(self.frame_2)
        self.searchNB.setGeometry(QtCore.QRect(10, 0, 101, 41))
        self.searchNB.setStyleSheet("background-color:rgb(255, 249, 246);\n"
"border:0px;\n"
"\n"
"border-radius:5px")
        self.searchNB.setIcon(icon6)
        self.searchNB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchNB.setObjectName("searchNB")
        self.label_78 = QtWidgets.QLabel(self.frame_2)
        self.label_78.setGeometry(QtCore.QRect(370, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_74 = QtWidgets.QLabel(self.frame_2)
        self.label_74.setGeometry(QtCore.QRect(350, 79, 151, 40))
        self.label_74.setStyleSheet("font: 9pt \"FontAwesome\";")
        self.label_74.setObjectName("label_74")
        self.modifyvalue = QtWidgets.QLineEdit(self.frame_2)
        self.modifyvalue.setGeometry(QtCore.QRect(470, 90, 111, 21))
        self.modifyvalue.setText("")
        self.modifyvalue.setObjectName("modifyvalue")
        self.commitTableModify = QtWidgets.QPushButton(self.frame_2)
        self.commitTableModify.setGeometry(QtCore.QRect(210, 85, 121, 31))
        self.commitTableModify.setStyleSheet("#commitTableModify{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitTableModify:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitTableModify.setObjectName("commitTableModify")
        self.commitTableDel = QtWidgets.QPushButton(self.frame_2)
        self.commitTableDel.setGeometry(QtCore.QRect(210, 40, 121, 31))
        self.commitTableDel.setStyleSheet("#commitTableDel{background:#CCFFCC;\n"
"border-radius:8px}\n"
"#commitTableDel:hover\n"
"{\n"
"background:#CCFF99\n"
"}")
        self.commitTableDel.setObjectName("commitTableDel")
        self.split_7 = QtWidgets.QFrame(self.page_12)
        self.split_7.setGeometry(QtCore.QRect(0, 130, 591, 2))
        self.split_7.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_7.setObjectName("split_7")
        self.roomTable = QtWidgets.QTableWidget(self.page_12)
        self.roomTable.setGeometry(QtCore.QRect(0, 130, 601, 401))
        self.roomTable.setObjectName("roomTable")
        self.roomTable.setColumnCount(5)
        self.roomTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.roomTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.roomTable.setHorizontalHeaderItem(4, item)
        self.stackedWidget_sub_3.addWidget(self.page_12)
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_sub.setCurrentIndex(1)
        self.stackedWidget_sub_2.setCurrentIndex(0)
        self.stackedWidget_sub_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "  客房信息"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "  办理入住"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "  预定登记和取消"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "   办理退房"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "  更新房源*"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "*表示需要最高权限"))
        self.Search.setPlaceholderText(_translate("MainWindow", "搜索"))
        self.toolButton_2.setText(_translate("MainWindow", "客房信息"))
        self.inputType.setItemText(0, _translate("MainWindow", "请选择..."))
        self.inputType.setItemText(1, _translate("MainWindow", "标准间（单人）"))
        self.inputType.setItemText(2, _translate("MainWindow", "标准间（双人）"))
        self.inputType.setItemText(3, _translate("MainWindow", "大床房"))
        self.inputType.setItemText(4, _translate("MainWindow", "总统套房"))
        self.label_22.setText(_translate("MainWindow", "房型："))
        self.label_23.setText(_translate("MainWindow", "房间状态："))
        self.label_24.setText(_translate("MainWindow", "预计入住时间："))
        self.label_25.setText(_translate("MainWindow", "价格范围："))
        self.label_26.setText(_translate("MainWindow", "—"))
        self.label_27.setText(_translate("MainWindow", "楼层："))
        self.inputstorey.setItemText(0, _translate("MainWindow", "请选择..."))
        self.inputstorey.setItemText(1, _translate("MainWindow", "2"))
        self.inputstorey.setItemText(2, _translate("MainWindow", "3"))
        self.inputstorey.setItemText(3, _translate("MainWindow", "4"))
        self.commitSearch.setText(_translate("MainWindow", "搜 索"))
        self.inputFree.setText(_translate("MainWindow", "只看空闲"))
        self.reset.setText(_translate("MainWindow", "重置"))
        self.toolButton_3.setText(_translate("MainWindow", "办理入住"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "  散客入住  "))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "团队入住 "))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "  预定入住"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "客户信息："))
        self.label_3.setText(_translate("MainWindow", "入住信息："))
        self.cname.setPlaceholderText(_translate("MainWindow", "姓名"))
        self.label_13.setText(_translate("MainWindow", "客户手机号："))
        self.cphone.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.label_9.setText(_translate("MainWindow", "客户姓名："))
        self.label_11.setText(_translate("MainWindow", "客户身份证："))
        self.cid.setPlaceholderText(_translate("MainWindow", "身份证"))
        self.label_14.setText(_translate("MainWindow", "客户年龄："))
        self.label_15.setText(_translate("MainWindow", "客户性别："))
        self.cage.setPlaceholderText(_translate("MainWindow", "年龄"))
        self.crid.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.label_10.setText(_translate("MainWindow", "房间号："))
        self.label_16.setText(_translate("MainWindow", "预计退房时间："))
        self.label_17.setText(_translate("MainWindow", "备注："))
        self.commitCheckin.setText(_translate("MainWindow", "确认入住"))
        self.male.setText(_translate("MainWindow", "男"))
        self.female.setText(_translate("MainWindow", "女"))
        self.label_12.setText(_translate("MainWindow", "团队名称："))
        self.label_4.setText(_translate("MainWindow", "团队入住："))
        self.label_18.setText(_translate("MainWindow", "团队预留手机号："))
        self.tphone.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.label_19.setText(_translate("MainWindow", "房间号："))
        self.label_5.setText(_translate("MainWindow", "团队信息："))
        self.tname.setPlaceholderText(_translate("MainWindow", "名称"))
        self.label_21.setText(_translate("MainWindow", "团队标识："))
        self.label_29.setText(_translate("MainWindow", "预计退房时间："))
        self.tid.setPlaceholderText(_translate("MainWindow", "标识"))
        self.trid.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.commitCheckinTeam.setText(_translate("MainWindow", "确认入住"))
        self.label_30.setText(_translate("MainWindow", "备注："))
        self.label_6.setText(_translate("MainWindow", "* 多个房间用逗号隔开"))
        self.label_46.setText(_translate("MainWindow", "个人预定入住："))
        self.label_47.setText(_translate("MainWindow", "团队预定入住："))
        self.label_48.setText(_translate("MainWindow", "预定时使用的身份证件："))
        self.cid_rtc.setPlaceholderText(_translate("MainWindow", "身份证件"))
        self.label_49.setText(_translate("MainWindow", "预定房号："))
        self.crid_rtc.setPlaceholderText(_translate("MainWindow", "房号"))
        self.tid_rtc.setPlaceholderText(_translate("MainWindow", "团队标识"))
        self.label_50.setText(_translate("MainWindow", "预定团队标识："))
        self.trid_rtc.setPlaceholderText(_translate("MainWindow", "房号"))
        self.label_51.setText(_translate("MainWindow", "预定房号："))
        self.label_52.setText(_translate("MainWindow", "* 多个房间用逗号隔开"))
        self.commitrtcC.setText(_translate("MainWindow", "确认入住"))
        self.commitrtcT.setText(_translate("MainWindow", "确认入住"))
        self.toolButton_4.setText(_translate("MainWindow", "登记预定"))
        self.label_7.setText(_translate("MainWindow", "客户信息："))
        self.label_8.setText(_translate("MainWindow", "预定信息："))
        self.cname_booking.setPlaceholderText(_translate("MainWindow", "姓名"))
        self.label_20.setText(_translate("MainWindow", "客户手机号："))
        self.cphone_booking.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.label_28.setText(_translate("MainWindow", "客户姓名："))
        self.label_31.setText(_translate("MainWindow", "客户身份证："))
        self.cid_booking.setPlaceholderText(_translate("MainWindow", "身份证"))
        self.label_32.setText(_translate("MainWindow", "客户年龄："))
        self.label_33.setText(_translate("MainWindow", "客户性别："))
        self.cage_booking.setPlaceholderText(_translate("MainWindow", "年龄"))
        self.crid_booking.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.label_34.setText(_translate("MainWindow", "房间号："))
        self.label_35.setText(_translate("MainWindow", "起止时间："))
        self.label_36.setText(_translate("MainWindow", "备注："))
        self.commitBookingClient.setText(_translate("MainWindow", "确认预定"))
        self.male_booking.setText(_translate("MainWindow", "男"))
        self.female_booking.setText(_translate("MainWindow", "女"))
        self.label_37.setText(_translate("MainWindow", "团队名称："))
        self.label_38.setText(_translate("MainWindow", "团队预定："))
        self.label_39.setText(_translate("MainWindow", "团队预留手机号："))
        self.tphone_booking.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.label_40.setText(_translate("MainWindow", "房间号："))
        self.label_41.setText(_translate("MainWindow", "团队信息："))
        self.tname_booking.setPlaceholderText(_translate("MainWindow", "名称"))
        self.label_42.setText(_translate("MainWindow", "团队标识："))
        self.label_43.setText(_translate("MainWindow", "起止时间："))
        self.tid_booking.setPlaceholderText(_translate("MainWindow", "标识"))
        self.trid_booking.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.commitBookingTeam.setText(_translate("MainWindow", "确认预定"))
        self.label_44.setText(_translate("MainWindow", "备注："))
        self.label_45.setText(_translate("MainWindow", "* 多个房间用逗号隔开"))
        self.cid_deb.setPlaceholderText(_translate("MainWindow", "身份证件"))
        self.label_53.setText(_translate("MainWindow", "* 多个房间用逗号隔开"))
        self.label_54.setText(_translate("MainWindow", "预定时使用的身份证件："))
        self.commitDeBookT.setText(_translate("MainWindow", "确认取消"))
        self.label_55.setText(_translate("MainWindow", "个人预定取消："))
        self.label_56.setText(_translate("MainWindow", "预定团队标识："))
        self.commitDeBookC.setText(_translate("MainWindow", "确认取消"))
        self.tid_deb.setPlaceholderText(_translate("MainWindow", "团队标识"))
        self.crid_deb.setPlaceholderText(_translate("MainWindow", "房号"))
        self.label_57.setText(_translate("MainWindow", "预定房号："))
        self.label_58.setText(_translate("MainWindow", "预定房号："))
        self.label_59.setText(_translate("MainWindow", "团队预定取消："))
        self.trid_deb.setPlaceholderText(_translate("MainWindow", "房号"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "  散客预定  "))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "团队预定  "))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", " 取消预定"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.toolButton_5.setText(_translate("MainWindow", "办理退房"))
        self.team_flag.setText(_translate("MainWindow", "团队"))
        self.single_flag.setText(_translate("MainWindow", "个人"))
        self.label_60.setText(_translate("MainWindow", "退房方式："))
        self.label_61.setText(_translate("MainWindow", "客户身份证或团队标识："))
        self.id_checkout.setPlaceholderText(_translate("MainWindow", "标识"))
        self.label_62.setText(_translate("MainWindow", "备注和评价："))
        self.label_63.setText(_translate("MainWindow", "起止时间："))
        self.rid_checkout.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.label_64.setText(_translate("MainWindow", "房间号："))
        self.label_65.setText(_translate("MainWindow", "支付方式："))
        self.paytype_checkout.setPlaceholderText(_translate("MainWindow", "支付方式"))
        self.commitCheckout.setText(_translate("MainWindow", "确认退房"))
        self.label_67.setText(_translate("MainWindow", "* 多个房间可用逗号隔开"))
        self.toolButton_6.setText(_translate("MainWindow", "更新房源"))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "  增添房间  "))
        item = self.listWidget_4.item(1)
        item.setText(_translate("MainWindow", "修改房源  "))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.commitAddRoom.setText(_translate("MainWindow", "确认增加"))
        self.label_71.setText(_translate("MainWindow", "房间单价(元/晚)："))
        self.label_68.setText(_translate("MainWindow", "房间号："))
        self.label_70.setText(_translate("MainWindow", "房间楼层："))
        self.rprice_add.setPlaceholderText(_translate("MainWindow", "单价"))
        self.rid_add.setPlaceholderText(_translate("MainWindow", "房间号"))
        self.rdesc_add.setPlaceholderText(_translate("MainWindow", "描述"))
        self.label_69.setText(_translate("MainWindow", "房间类型："))
        self.label_72.setText(_translate("MainWindow", "描述："))
        self.label_84.setText(_translate("MainWindow", "输入要增设的房间信息："))
        self.rtype_add.setItemText(0, _translate("MainWindow", "请选择..."))
        self.rtype_add.setItemText(1, _translate("MainWindow", "标准间（单人）"))
        self.rtype_add.setItemText(2, _translate("MainWindow", "标准间（双人）"))
        self.rtype_add.setItemText(3, _translate("MainWindow", "大床房"))
        self.rtype_add.setItemText(4, _translate("MainWindow", "总统套房"))
        self.rstorey_add.setItemText(0, _translate("MainWindow", "请选择..."))
        self.rstorey_add.setItemText(1, _translate("MainWindow", "2"))
        self.rstorey_add.setItemText(2, _translate("MainWindow", "3"))
        self.rstorey_add.setItemText(3, _translate("MainWindow", "4"))
        self.label_66.setText(_translate("MainWindow", "展示图片选择："))
        self.scan.setText(_translate("MainWindow", "浏览"))
        self.path.setPlaceholderText(_translate("MainWindow", "图片路径"))
        self.searchNB.setText(_translate("MainWindow", "检索房源"))
        self.label_78.setText(_translate("MainWindow", "*选中表格内可以进行修改和删除操作"))
        self.label_74.setText(_translate("MainWindow", "选中部分修改为："))
        self.modifyvalue.setPlaceholderText(_translate("MainWindow", "修改值"))
        self.commitTableModify.setText(_translate("MainWindow", "确认修改"))
        self.commitTableDel.setText(_translate("MainWindow", "确认删除"))
        item = self.roomTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "房间号"))
        item = self.roomTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "房间类型"))
        item = self.roomTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "房间楼层"))
        item = self.roomTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "房间价格(元/晚)"))
        item = self.roomTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "备注说明"))
